services: # Список всі контейнерів
  app: # Назва сервісу
    build: . # Він каже: "Docker, візьми Dockerfile у поточній папці (крапка .) і збери з нього образ".
    container_name: my_web_app_compose
    ports:
      - "3000:3000" # Перше число — порт на твоєму ноутбуці, друге — порт всередині контейнера.
      - "5000:5000/udp" # Відкриття Socket-порту. Додаємо /udp, якщо твій сервер використовує цей протокол
    volumes: # Секція для синхронізації файлів.
      - ./storage:/app/storage # Це "магія", яка пов'язує твою папку storage з проектом у VS Code та папку /app/storage 
                 # всередині контейнера. Завдяки цьому твій data.json зберігається на диску, а не зникає при зупинці Docker.